Wim243 adding constructors laurette
LauretteBuitenhuis/BookRental-Backend pull request #13
Opened 2022-12-21 14:37 UTC by LauretteBuitenhuis

Ik heb in User de reservations, loans & token uit de constructor gelaten. Klopt dit?

2022-12-21 15:56 UTC, lisalootens requested changes
Hi, thanks voor de PR. Lijkt me prima.

Ik zie alleen dat je merge conflicts hebt, die zullen eerst opgelost moeten worden.
Verder zou ik TODO ook uit je code halen of eventueel een ticketnummer meegeven.

Lekker bezig

2022-12-21 15:56 UTC, lisalootens commented on src/main/java/nl/workingtalent/bookrental/controller/UserController.java
> +		//TODO add error codes
Remove TODO

2022-12-21 15:56 UTC, lisalootens commented on src/main/java/nl/workingtalent/bookrental/controller/UserController.java
> +		// TODO constructor
Remove TODO

2022-12-21 15:56 UTC, lisalootens commented on src/main/java/nl/workingtalent/bookrental/dto/LoginDto.java
> +import com.fasterxml.jackson.annotation.JsonCreator;
Nice!

2022-12-21 15:56 UTC, lisalootens commented on src/main/java/nl/workingtalent/bookrental/dto/NewUserDto.java
> +	// TODO id (request & send dto) & constructor
Remove TODO

2022-12-22 10:03 UTC, TychoZaal commented on src/main/java/nl/workingtalent/bookrental/dto/NewUserDto.java
> +	public NewUserDto(@JsonProperty("firstName") String firstName, @JsonProperty("lastName") String lastName, @JsonProperty("email") String email, @JsonProperty("password") String password, @JsonPropert
Misschien een enter na String lastname voor readability

2022-12-22 10:25 UTC, lisalootens approved these changes

2022-12-22 10:26 UTC, merged